export function normalizeRoleCode(roleCode: string) {
  const normalizedRole = roleCode
    .trim()
    .toUpperCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")

  const roleAliases: Record<string, string> = {
    ADMINISTRACION: "ADMIN",
    ADMINISTRADOR: "ADMIN",
    ASESOR_DE_SERVICIO: "ASESOR",
    ASESOR_SERVICIO: "ASESOR",
    SUPER_ADMIN: "ADMIN",
    SUPERADMIN: "ADMIN",
    RECEPCIONISTA: "RECEPCION",
    REPUESTO: "REPUESTOS",
    CLIENTES: "CLIENTE",
    BAHIA_DE_ENDEREZADA: "DEP_ENDEREZADA",
    BAHIA_ENDEREZADA: "DEP_ENDEREZADA",
    DEP_ENDEREZADO: "DEP_ENDEREZADA",
    ENDEREZADA: "DEP_ENDEREZADA",
    ENDEREZADO: "DEP_ENDEREZADA",
    BAHIA_DE_REPARACION_PINTURA: "DEP_REPARACION_PINTURA",
    BAHIA_DE_REPARACION_Y_PINTURA: "DEP_REPARACION_PINTURA",
    BAHIA_REPARACION_PINTURA: "DEP_REPARACION_PINTURA",
    DEP_PINTURA: "DEP_REPARACION_PINTURA",
    PINTURA: "DEP_REPARACION_PINTURA",
    REPARACION_PINTURA: "DEP_REPARACION_PINTURA",
    REPARACION_Y_PINTURA: "DEP_REPARACION_PINTURA",
    BAHIA_DE_ENSAMBLAJE: "DEP_ENSAMBLAJE",
    BAHIA_ENSAMBLAJE: "DEP_ENSAMBLAJE",
    DEP_ENSAMBLE: "DEP_ENSAMBLAJE",
    ENSAMBLAJE: "DEP_ENSAMBLAJE",
    ENSAMBLE: "DEP_ENSAMBLAJE",
    BAHIA_DE_MECANICA: "DEP_MECANICA",
    BAHIA_MECANICA: "DEP_MECANICA",
    MECANICA: "DEP_MECANICA",
    MECANICO: "DEP_MECANICA",
    BAHIA_DE_LAVADO_CALIDAD: "DEP_LAVADO_CALIDAD",
    BAHIA_DE_LAVADO_Y_CONTROL_DE_CALIDAD: "DEP_LAVADO_CALIDAD",
    BAHIA_LAVADO_CALIDAD: "DEP_LAVADO_CALIDAD",
    CALIDAD: "DEP_LAVADO_CALIDAD",
    CONTROL_DE_CALIDAD: "DEP_LAVADO_CALIDAD",
    DEP_LAVADO: "DEP_LAVADO_CALIDAD",
    LAVADO: "DEP_LAVADO_CALIDAD",
    LAVADO_CALIDAD: "DEP_LAVADO_CALIDAD",
    LAVADO_Y_CONTROL_DE_CALIDAD: "DEP_LAVADO_CALIDAD",
  }

  return roleAliases[normalizedRole] ?? normalizedRole
}
