export const ESTADO_PROCESO_CODES = {
  ASESOR: "ASESOR",
  JEFE_TALLER: "JEFE_TALLER",
  REPUESTOS: "REPUESTOS",
  PROGRAMAR_CITA: "PROGRAMAR_CITA",
  ENDEREZADA: "ENDEREZADA",
  PINTURA: "PINTURA",
  ENSAMBLAJE: "ENSAMBLAJE",
  MECANICA: "MECANICA",
  LAVADO: "LAVADO",
  FINALIZADO: "FINALIZADO",
} as const

export type EstadoProcesoCode =
  (typeof ESTADO_PROCESO_CODES)[keyof typeof ESTADO_PROCESO_CODES]

export const ESTADO_PROCESO_LABELS: Record<EstadoProcesoCode, string> = {
  ASESOR: "Asesoria / Ingreso",
  JEFE_TALLER: "Revision Jefe de Taller",
  REPUESTOS: "Gestion de Repuestos",
  PROGRAMAR_CITA: "Programacion de Cita",
  ENDEREZADA: "Bahia de Enderezada",
  PINTURA: "Bahia de Preparacion y Pintura",
  ENSAMBLAJE: "Bahia de Ensamblaje",
  MECANICA: "Bahia de Mecanica",
  LAVADO: "Lavado y Control de Calidad",
  FINALIZADO: "Entregado a Satisfaccion",
}

export const INITIAL_WORK_ORDER_ESTADO_PROCESO_CODE =
  ESTADO_PROCESO_CODES.ASESOR

export const OPERATIONAL_ESTADO_PROCESO_CODES = [
  ESTADO_PROCESO_CODES.ENDEREZADA,
  ESTADO_PROCESO_CODES.PINTURA,
  ESTADO_PROCESO_CODES.ENSAMBLAJE,
  ESTADO_PROCESO_CODES.MECANICA,
  ESTADO_PROCESO_CODES.LAVADO,
] as const

export const WORKSHOP_LEAD_TARGET_ESTADO_PROCESO_CODES = [
  ESTADO_PROCESO_CODES.REPUESTOS,
  ESTADO_PROCESO_CODES.PROGRAMAR_CITA,
  ...OPERATIONAL_ESTADO_PROCESO_CODES,
] as const

export const SPARE_PARTS_TARGET_ESTADO_PROCESO_CODES = [
  ESTADO_PROCESO_CODES.PROGRAMAR_CITA,
  ...OPERATIONAL_ESTADO_PROCESO_CODES,
] as const

export const SCHEDULE_APPOINTMENT_TARGET_ESTADO_PROCESO_CODES = [
  ...OPERATIONAL_ESTADO_PROCESO_CODES,
] as const

export const OPERATIONAL_TARGET_ESTADO_PROCESO_CODES = [
  ...OPERATIONAL_ESTADO_PROCESO_CODES,
  ESTADO_PROCESO_CODES.FINALIZADO,
] as const
