export const ESTADO_PROCESO_CODES = {
  ASESOR: "ASESOR",
  JEFE_TALLER: "JEFE_TALLER",
  REPUESTOS: "REPUESTOS",
  PROGRAMAR_CITA: "PROGRAMAR_CITA",
  ENDEREZADA: "ENDEREZADA",
  PINTURA: "PINTURA",
  ENSAMBLAJE: "ENSAMBLAJE",
  MECANICA: "MECANICA",
  LAVADO: "LAVADO",
  FINALIZADO: "FINALIZADO",
  CONTROL_CALIDAD: "CONTROL_CALIDAD",
  AUTO_INGRESADO: "AUTO_INGRESADO",
  ENTREGAR_AUTO: "ENTREGAR_AUTO",
} as const

export type EstadoProcesoCode =
  (typeof ESTADO_PROCESO_CODES)[keyof typeof ESTADO_PROCESO_CODES]

export const ESTADO_PROCESO_LABELS: Record<EstadoProcesoCode, string> = {
  ASESOR: "Asesoría / Ingreso",
  JEFE_TALLER: "Revisión Jefe de Taller",
  REPUESTOS: "Gestión de Repuestos",
  PROGRAMAR_CITA: "Programación de Cita",
  ENDEREZADA: "Bahía de Enderezada",
  PINTURA: "Bahía de Preparación y Pintura",
  ENSAMBLAJE: "Bahía de Ensamblaje",
  MECANICA: "Bahía de Mecánica",
  LAVADO: "Lavado y Control de Calidad",
  FINALIZADO: "Entregado a Satisfacción",
  CONTROL_CALIDAD: "Control de Calidad",
  AUTO_INGRESADO: "Auto Ingresado",
  ENTREGAR_AUTO: "Auto en proceso de entrega",
}

export const INITIAL_WORK_ORDER_ESTADO_PROCESO_CODE =
  ESTADO_PROCESO_CODES.ASESOR

export const GENERALLY_ASSIGNABLE_BAY_ESTADO_PROCESO_CODES = [
  ESTADO_PROCESO_CODES.ENDEREZADA,
  ESTADO_PROCESO_CODES.PINTURA,
  ESTADO_PROCESO_CODES.ENSAMBLAJE,
  ESTADO_PROCESO_CODES.MECANICA,
  ESTADO_PROCESO_CODES.LAVADO,
  ESTADO_PROCESO_CODES.CONTROL_CALIDAD,
] as const

export const OPERATIONAL_ESTADO_PROCESO_CODES = [
  ...GENERALLY_ASSIGNABLE_BAY_ESTADO_PROCESO_CODES,
  ESTADO_PROCESO_CODES.ENTREGAR_AUTO,
] as const

export const WORKSHOP_LEAD_TARGET_ESTADO_PROCESO_CODES = [
  ESTADO_PROCESO_CODES.REPUESTOS,
  ESTADO_PROCESO_CODES.PROGRAMAR_CITA,
  ...GENERALLY_ASSIGNABLE_BAY_ESTADO_PROCESO_CODES,
] as const

export const SPARE_PARTS_TARGET_ESTADO_PROCESO_CODES = [
  ESTADO_PROCESO_CODES.PROGRAMAR_CITA,
  ...GENERALLY_ASSIGNABLE_BAY_ESTADO_PROCESO_CODES,
] as const

export const SCHEDULE_APPOINTMENT_TARGET_ESTADO_PROCESO_CODES = [
  ESTADO_PROCESO_CODES.AUTO_INGRESADO,
] as const

export const OPERATIONAL_TARGET_ESTADO_PROCESO_CODES = [
  ...GENERALLY_ASSIGNABLE_BAY_ESTADO_PROCESO_CODES,
] as const
